
--DROP TABLE clinicabd.PACIENTE;
CREATE TABLE clinicabd.PACIENTE
(
ID  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(255),
RG VARCHAR(20),
CPF VARCHAR(20),
SEXO VARCHAR(1),	

ID_RESPONSAVEL INTEGER,
ID_CONTATO INTEGER,
ID_ENDERECO INTEGER

)
;

--DROP TABLE clinicabd.MEDICO;
CREATE TABLE clinicabd.MEDICO
(
ID  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
CRM VARCHAR(20),
NOME VARCHAR(255),
CPF VARCHAR(20),

ID_CONTATO INTEGER,
ID_ENDERECO INTEGER

)
;

--DROP TABLE clinicabd.CONTATO;
CREATE TABLE clinicabd.CONTATO
(
ID  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(255),
TELEFONE VARCHAR(20),
CELULAR VARCHAR(20)
)
;

--DROP TABLE clinicabd.ENDERECO;
CREATE TABLE clinicabd.ENDERECO
(
ID  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
ENDERECO VARCHAR(255),
CIDADE VARCHAR(255),
CEP VARCHAR(20),
BAIRRO VARCHAR(255)
)
;

--DROP TABLE clinicabd.CONSULTA
CREATE TABLE clinicabd.CONSULTA
(
ID  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,

ID_MEDICO INTEGER,
ID_PACIENTE INTEGER,
ID_MEDICAMENTO INTEGER,
ID_PAGAMENTO INTEGER
)
;

--DROP TABLE clinicabd.PAGAMENTO;
CREATE TABLE clinicabd.PAGAMENTO
(
ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
VALOR DOUBLE,
DESCRICAO VARCHAR(255)
)
;

--DROP TABLE clinicabd.MEDICAMENTO;
CREATE TABLE clinicabd.MEDICAMENTO
(
ID  INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(255),
DESCRICAO VARCHAR(255)
)
;